service: java-output-extractor
app: outputExtractor
frameworkVersion: '2'

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221

  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:Get"
        - "s3:List"
        - "s3:GetObject"
        - "s3:GetBucketLocation"
        - "s3:ListBucket"
      Resource: "*"
  environment:
    REGION: ${env:REGION}

package:
  artifact: build/distributions/outputExtractor.zip

functions:
  outputExtractor:
    handler: com.serverless.LambdaHandler
    name: "outputExtractor"